### ISSUE TITLE
Builder Image Failed

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid-openshift-examples#69]
Hi

Below is my yaml file and when i push it to Openshift it throws an error of "builder image failed". I have no idea what it means and i dont know how to get more logs. Are you able to assist please?

Thanks,

> apiVersion: teiid.io/v1alpha1
kind: VirtualDatabase
metadata:
  name: dv-customer
spec:
  replicas: 1
  datasources:
    - name: tabdev
      type: postgresql
      properties:
        - name: SPRING_DATASOURCE_PGSQL_USERNAME
          value: <USERNAME>
        - name: SPRING_DATASOURCE_PGSQL_PASSWORD
          value: <SECRET>
        - name: SPRING_DATASOURCE_PGSQL_JDBCURL
          value: jdbc:postgresql://IP:8060/workgroup
        - name: SPRING_DATASOURCE_PGSQL_IMPORTER_SCHEMA_NAME
          value: public
        - name: SPRING_DATASOURCE_PGSQL_DRIVER_CLASS_NAME
          value: org.postgresql.Driver
  resources:
    memory: 1024Mi
    cpu: 2.0
  build:
    source:
     dependencies:
        - org.postgresql:postgresql:42.2.5    
     ddl: |
        CREATE DATABASE tabdev;
        USE DATABASE tabdev;
        CREATE SERVER pgsql TYPE 'NONE' FOREIGN DATA WRAPPER postgresql;
        CREATE SCHEMA tabdev SERVER pgsql;
        SET SCHEMA tabdev;
        IMPORT FOREIGN SCHEMA public FROM SERVER pgsql INTO tabdev
            OPTIONS(
        	importer.tableTypes 'TABLE',"importer.tableNamePattern" 'data%'
        );
    mavenRepositories:
     private : https://artifactory.server.net/artifactory/fit-dal-all-repos

**Comment by rareddy** [comment]
Looks in `teiid-operator` log for details

**Comment by yapnel** [comment]
I'm new to openshift. May i know where the teiid-operator log file is located?

Btw - i am using Code Ready Container

Thanks

**Comment by yapnel** [comment]
Hitting this error while trying to view the operator logs. Do you know how to resolve it?


> C:\Temp>oc project dv-project
Now using project "dv-project" on server "https://api.crc.testing:6443".

>C:\Temp>oc get pods
NAME                           READY   STATUS    RESTARTS   AGE
dv-operator-756ffd5f84-sprwb   1/1     Running   0          18m

>C:\Temp>oc logs dv-operator-756ffd5f84-sprwb
Error from server: Get https://192.168.51.212:10250/containerLogs/dv-project/dv-operator-756ffd5f84-sprwb/dv-operator: x509: cannot validate certificate for 192.168.51.212 because it doesn't contain any IP SANs

**Comment by rareddy** [comment]
hmm, looks like you are running into some security-related issues, maybe better asked OpenShift forum for better diagnosis

**Comment by yapnel** [comment]
Yes. Got a response from CRC and it is fixed in the latest version.

I will leave this issue open as I'm still facing the build image error that needs investigating at my end

Thanks

**Comment by yapnel** [comment]
Hi

The log indicates the below error

>org.apache.maven.plugin.PluginResolutionException: Plugin org.teiid:vdb-codegen-plugin:1.2.1.fuse-750013-redhat-00001 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.teiid:vdb-codegen-plugin:jar:1.2.1.fuse-750013-redhat-00001

> Caused by: org.apache.maven.wagon.authorization.AuthorizationException: Not authorized by proxy , ReasonPhrase:Proxy Authentication Required.

There is a warning about this too
> Starting S2I Java Build .....
S2I source build for Maven detected
WARNING: Proxy URL for https contains authentication credentials, these are not supported by java
WARNING: Proxy URL for http contains authentication credentials, these are not supported by java
Using MAVEN_OPTS '-Dhttps.proxyHost=11.191.100.206 -Dhttps.proxyPort=8080 -Dhttp.proxyHost=11.191.100.206 -Dhttp.proxyPort=8080 -Dhttp.nonProxyHosts=*.cluster.local|*.svc|*.testing|10.128.0.0/14|127.0.0.1|172.17.27.126|172.30.0.0/16|192.168.126.0/24|api-int.crc.testing|etcd-0.crc.testing|localhost -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError'

I need to specify the username and password for the PROXY server to get to the internet to download the artefacts. Is it something i can set somewhere?

thanks

**Comment by rareddy** [comment]
You re using RedHat supplied Data Virtualiztion Operator which requires RedHar customer portal access to install. There is also community version if you want to try. Remove this completely first before installing the other one

**Comment by yapnel** [comment]
I am using my RH customer portal account though. I think this is the proxy on my corporate env. Is there a way to set the login for maven during the build?

**Comment by rareddy** [comment]
If you mean login into private maven proxy, last week I added a feature to supply a custom `settings.xml` that define these values, but that is not released yet. If you want yo can build from master. https://issues.redhat.com/browse/TEIIDTOOLS-950

**Comment by yapnel** [comment]
I was looking at the documentation and i followed the example to specify the proxy. Is this correct? 
When will this be available? Maven inside CRC Openshift needs to go via the PROXY server to get on to the internet to fetch the packages. Unless there is a way to use my internal Artefactory server to fetch instead?

`kind:ConfigMap
apiVersion: v1
metadata:
  name: teiid-maven-settings
  namespace: dv-customer
data:
  settings.xml: >-
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
    https://maven.apache.org/xsd/settings-1.0.0.xsd">
      <proxies>
        <proxy>
         <active>true</active>
         <protocol>http</protocol>
         <username><REDACTED></username>
         <password><REDACTED></password>
         <host>11.191.100.206</host>
         <port>8080</port>
<nonProxyHosts>localhost|127.0.0.1|11.125.64.157</nonProxyHosts>
        </proxy>
      </proxies>
    </settings>`

**Comment by rareddy** [comment]
Yes looks right. I do not have set date for it, but most probably in next week or the following week. 

It is not a proxy, but alternative location to specify a private maven repo for building artifacts rather than going to maven central. I never used proxy inside settings.xml, but yeah looks like that should work if point to your proxy I think.

**Comment by yapnel** [comment]
Any timeline when is the next release?

**Comment by rareddy** [comment]
Hopefully, I will submit PR to OperatorHub tomorrow or early next week. I also put in support for PROXY settings yesterday https://issues.redhat.com/browse/ENTESB-13175. It would great if there is way you can install on your cluster from master and test before I push it?

**Comment by yapnel** [comment]
I have no idea how to do that to help you test.

**Comment by yapnel** [comment]
I have installed the 0.20 operator and can confirmed the build was successful.

However, I have encountered another issue that may need your advise please.

`Caused by: java.lang.IllegalArgumentException: dataSource or dataSourceClassName or jdbcUrl is required.`

Below is my VBD CR. What could be wrong with it please?
```
apiVersion: teiid.io/v1alpha1
kind: VirtualDatabase
metadata:
name: dv-customer
spec:
  replicas: 1
  datasources:
    - name: tabdev
      type: postgresql
      properties:
        - name: SPRING_DATASOURCE_PGSQL_USERNAME
          value:
        - name: SPRING_DATASOURCE_PGSQL_PASSWORD
          value:
        - name: SPRING_DATASOURCE_PGSQL_JDBCURL
          value: jdbc:postgresql://IP:8060/workgroup
        - name: SPRING_DATASOURCE_PGSQL_IMPORTER_SCHEMA_NAME
          value: public
        - name: SPRING_DATASOURCE_PGSQL_DRIVER_CLASS_NAME
          value: org.postgresql.Driver
  resources:
  memory: 1024Mi
  cpu: 2.0
  build:
    source:
      dependencies:
        - org.postgresql:postgresql:42.2.5
      ddl: |
        CREATE DATABASE tabdev;
        USE DATABASE tabdev;
        CREATE SERVER pgsql TYPE 'NONE' FOREIGN DATA WRAPPER postgresql;
        CREATE SCHEMA tabdev SERVER pgsql;
        SET SCHEMA tabdev;
        IMPORT FOREIGN SCHEMA public FROM SERVER pgsql INTO tabdev
        OPTIONS(
          importer.tableTypes 'TABLE',"importer.tableNamePattern" 'data%'
        );
      mavenRepositories:
        private : https://artifactory.server.net/artifactory/fit-dal-all-repos
```

**Comment by rareddy** [comment]
You do not need to build from the code anymore for `0.2.0` version, this should be now available on OperatorHub.io, so just by going to the left nav menu in OpenShift 4.x and searching for Teiid should bring this version up and you can install from there.

The particular error you are seeing is due to the issue https://issues.redhat.com/browse/ENTESB-11938

Following that, your CR should look like

```yaml
apiVersion: teiid.io/v1alpha1
kind: VirtualDatabase
metadata:
name: dv-customer
spec:
  replicas: 1
  datasources:
    - name: tabdev
      type: postgresql
      properties:
        - name: username
          value: xxxx
        - name: password
          value: xxxx
        - name: jdbc-url
          value: jdbc:postgresql://IP:8060/workgroup
        - name: driver-class-name
          value: org.postgresql.Driver
  resources:
  memory: 1024Mi
  cpu: 2.0
  build:
    source:
      dependencies:
        - org.postgresql:postgresql:42.2.5
      ddl: |
        CREATE DATABASE tabdev;
        USE DATABASE tabdev;
        CREATE SERVER pgsql TYPE 'NONE' FOREIGN DATA WRAPPER postgresql;
        CREATE SCHEMA tabdev SERVER pgsql;
        SET SCHEMA tabdev;
        IMPORT FOREIGN SCHEMA public FROM SERVER pgsql INTO tabdev
        OPTIONS(
          importer.tableTypes 'TABLE',"importer.tableNamePattern" 'data%', "importer.schemaName" 'public'
        );
      mavenRepositories:
        private : https://artifactory.server.net/artifactory/fit-dal-all-repos
```
So the previous Environment properties turned into specific data source properties, where we do not need to bring Spring Boot specific properties into User level and these are much more human-readable. The previous ENV properties still continue to work. Documentation on properties is still pending, I hope to get to very soon. For example see a sample CR here https://github.com/teiid/teiid-operator/blob/master/deploy/crds/vdb_from_ddl.yaml

Love to hear your feedback on this.
